# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email:"jcontardo@miaundes.cl", password:"123456")
Ingredient.create(name:"Pepperoni")
Ingredient.create(name:"Onion")
Ingredient.create(name:"Ham")
Ingredient.create(name:"Cheese")
Ingredient.create(name:"Chicken")
Ingredient.create(name:"Italian Meat")
Crust.create(crust_type:"Regular", price:4500)
Crust.create(crust_type:"Thin", price:3000)
Recipe.create(price:8500)
Recipe.create(price:9000)
Recipe.create(price:6000)
Recipe.create(price:7800)
RecipeIngredient.create(recipe_id:1, ingredient_id:1)
RecipeIngredient.create(recipe_id:1, ingredient_id:3)
RecipeIngredient.create(recipe_id:1, ingredient_id:4)
RecipeIngredient.create(recipe_id:2, ingredient_id:1)
RecipeIngredient.create(recipe_id:2, ingredient_id:2)
RecipeIngredient.create(recipe_id:2, ingredient_id:3)
RecipeIngredient.create(recipe_id:2, ingredient_id:5)
RecipeIngredient.create(recipe_id:3, ingredient_id:6)
RecipeIngredient.create(recipe_id:3, ingredient_id:2)
RecipeIngredient.create(recipe_id:3, ingredient_id:1)
RecipeIngredient.create(recipe_id:4, ingredient_id:6)
RecipeIngredient.create(recipe_id:4, ingredient_id:2)
RecipeIngredient.create(recipe_id:4, ingredient_id:1)
Pizza.create(name:"Joe's Pizza",recipe_id:1, crust_id:1)
Pizza.create(name:"Original Pizza",recipe_id:1, crust_id:2)
Pizza.create(name:"Extra Pizza",recipe_id:2, crust_id:1)
Pizza.create(name:"Heaven Pizza",recipe_id:2, crust_id:2)
Pizza.create(name:"Ocean Pizza",recipe_id:3, crust_id:1)
Pizza.create(name:"Caribean Pizza",recipe_id:3, crust_id:2)
Pizza.create(name:"Sky Pizza",recipe_id:4, crust_id:1)
Pizza.create(name:"Pizza Planet", recipe_id:4, crust_id:2)